apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnetworks.azure.backstack.dev
  labels:
    provider: azure
    type: delab
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: azure.backstack.dev/v1alpha1
    kind: XNetwork
  patchSets:
  - name: network-id
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.id
      toFieldPath: metadata.labels[azure.caas.upbound.io/network-id]
  - name: region
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
  resources:
  - name: virtual-network
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
      spec:
        forProvider:
          resourceGroupName: spec.parameters.resourceGroup
          addressSpace:
          - 192.168.0.0/16
    patches:
    - type: PatchSet
      patchSetName: network-id
    - type: PatchSet
      patchSetName: region
    - fromFieldPath: spec.parameters.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-vnet"
    - type: ToCompositeFieldPath
      fromFieldPath: spec.parameters.id
      toFieldPath: status.vnet
      transforms:
      - type: string
        string:
          fmt: "%s-vnet"
    - type: ToCompositeFieldPath
      fromFieldPath: spec.parameters.resourceGroup
      toFieldPath: status.resourceGroup
  - name: subnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      spec:
        forProvider:
          resourceGroupName: spec.parameters.resourceGroup
          virtualNetworkNameSelector:
            matchControllerRef: true
          addressPrefixes:
          - 192.168.1.0/24
    patches:
    - type: PatchSet
      patchSetName: network-id
    - fromFieldPath: spec.parameters.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-sn"
    - type: ToCompositeFieldPath
      fromFieldPath: status.id
      toFieldPath: status.subnet
