apiVersion: backstack.dev/v1alpha1
kind: AKSCluster
metadata:
  name: de-aks-backstack
  namespace: default
spec:
  parameters:
    id: de-aks-backstack
    region: "East US"
    version: 1.27.3
    nodes:
      count: 3
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: de-aks-backstack-kubeconfig
  publishConnectionDetailsTo:
    name: de-aks-backstack/de-aks-backstack-kubeconfig
    configRef:
      name: vault
